### ISSUE TITLE
Говно код

### ISSUE THREAD

**Issue by marcenavuc** [pavelslabikov/python-1#1]

**Comment by pavelslabikov** [comment]
нет соси

**Comment by marcenavuc** [comment]
Может хватит бухтеть и дестабилизировать ситуацию в стране?
Есть инфа от знающего человека, что у нас в стране скоро ожидаются реальные изменения. После того, как стабилизируют ситуацию в Сирии, уничтожат ИГИЛ. Тогда везде и сформируют торговый альянс со средним востоком. Нефть поднимут и будут держать, Европа ничего не сможет сделать. Сейчас главное не бухтеть.

От нас требуется сидеть тихо. После того, как все сделают, все будет у нас хорошо. Всем устроят довольствие, как Саудовским гражданам - каждый будет кататься в масле. Главное сейчас сидеть тихо и не суетиться. Никаких митингов, никаких навальных. Просто переждать и всё будет хорошо, там все схвачено.
